version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/horizon-core-web

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build OpenNMS Horizon Docker image
          command: |
            docker build -t horizon-core-web-${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM} .
